### ISSUE TITLE
Q2 documentation updates

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1428]
README:

- [x] Update Rafiki planning call time
- [ ] Rename “Interledger Docs” to “Interledger Specs” (and update the link)

`architecture.md`

- [ ] Update excalidraw diagram
- [ ] Add GraphQL admin API description to `auth` service section

`admin-api.md`

- [x] Include auth admin API (moved to #1651)

`connector.md`

- [ ] Remove "often for Web Monetization" from Local Stream Server
- [ ] Remove “and more!” from Packet Rejection (and remove “including”)

`accounts-and-transfers.md`

- [ ] Link double-entry accounting to Wiki page
- [ ] Make it clear that PP and IP liquidity accounts get created on the fly, while asset and peer created when they get created via GraphQL calls

`grant-interaction.md`

- [ ] Put the diagram at the beginning
- [x] Endpoints for the API calls should link to the OpenAPI specs (that will be added separately) (moved to #1668)

`key-registry.md`

- [x] Should be moved to the Open Payments website
- [x] Should be turned into a document explaining what it means for an Admin to add keys to a payment pointer (moved to #1667)
