### ISSUE TITLE
Add fee structure to incoming payment request and response

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1638]
## Context

- on the Incoming Payment request, the creator of the incoming payment can indicate whether the sender should pay the receiver's fees (remittance use case)
- on the Incoming Payment response, include fee structure if requested. (The reason it is not the actual fee amount is because the incomingAmount for the payment is optional) 
- see OP spec or [PR](https://github.com/interledger/open-payments/issues/274)

## Todo
- [ ] add `feeId?: uuid` column to incoming payments table 
- [ ] set `feeId` in incoming payments table if `feeStructure=true` in the incoming payment creation request
- [ ] add fee structure to the incoming payment response if `feeId` is set for the incoming payment
- [ ] update docs
