### ISSUE TITLE
Calculate and add fees to quote

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1639]
## Context

The `sendAmount` field should be called `debitAmount`, because it includes the total amount that is going to be debited from the user's account, including fees. The sending fees should be added to the `debitAmount` after Rafiki does the rate probe. 

## Todo
- [ ] add `feeId?: uuid` column to quotes table
- [ ] rename `sendAmount` -> `debitAmount` in quote response
- [ ] calculate sending fee based on `feeId`
- [ ] add sending fee to `debitAmount`
  ```
  // Quote response
    {  ...,
       "receiveAmount": {
            "value": "10000",
            "assetCode": "USD",
            "assetScale": 2
        },
        "debitAmount": { //includes all fees
            "value": "10310",
            "assetCode": "USD",
            "assetScale": 2
        }
    }
  ```
- [ ] update docs
