### ISSUE TITLE
Payment pointer liquidity event: update `received`

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1650]
## Context

All webhook events include liquidity in the `AmountJSON` type, i.e.
```
{
  value: string
  assetCode: string
  assetScale: number
}
```
However, the payment pointer webhook event only returns `received: string`.  See [here](https://github.com/interledger/rafiki/blob/f1a396c1d4a300d220f83267e0846daaa4c6afe4/packages/backend/src/open_payments/payment_pointer/model.ts#L113).

## Todo
- [ ] update the `PaymentPointerData` to remove `received: string` and add `receivedAmount: AmountJSON`
- [ ] update the webhook open api spec
- [ ] make changes in mock ASE
- [ ] update the docs

**Comment by nayaldivya** [comment]
Hi! Please assign this to me
