### ISSUE TITLE
Add documentation for Auth Admin API

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1651]
## Overview

We should add the Auth Admin API to the rafiki.dev documentation. 
This requires us to generate the graphql markdown types for the Auth Admin API schemas. 

I imagine the documation page could look something like this:

<img width="298" alt="Screenshot 2023-07-26 at 13 37 24" src="https://github.com/interledger/rafiki/assets/15069181/89dff29a-9d4e-4385-acc6-93465973c8f3">

## Tasks

- [ ] Add new page to the documentation for auth admin API
- [ ] Generate markdown doc files from the auth admin API schema
- [ ] Update Github actions to fail checks if auth admin API changes are made, but the documentation hasn't changed
