### ISSUE TITLE
Display payment liquidity on Admin UI and allow deposit/withdrawal

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1696]
## Context

Payment and payment pointer liquidity is now returned with the query for those. This liquidity should be displayed like we display asset and peer liquidity and we should allow deposit and withdrawal from that view.

## Depends on
- https://github.com/interledger/rafiki/issues/1693
- https://github.com/interledger/rafiki/issues/1694

## Todos
- [x] Make `/payments` page
- [x] Make `/payments/{id}` page
- [x] Show Liquidity on each payment
- [x] Show Liquidity on each payment pointer
- [x] Allow depositing and withdrawing liquidity
