### ISSUE TITLE
Deprecating event liquidity

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1697]
## Context

Currently, we deposit and withdraw liquidity as follows:
* asset liquidity -> based on asset id
* peer liquidity -> based on peer id
* payment pointer l. -> based on payment pointer id
* incoming payment l. -> based on event id
* outgoing payment l. -> based on event id

To standardize, we want to also allow depositing and withdrawing liquidity by payment id. We want to deprecate `eventId`-based liquidity management. 

## Todos
- [x] https://github.com/interledger/rafiki/issues/1693
- [x] https://github.com/interledger/rafiki/issues/1694
- [x] https://github.com/interledger/rafiki/issues/1695
- [x] https://github.com/interledger/rafiki/issues/1696

Related
- https://github.com/interledger/rafiki/issues/413
- https://github.com/interledger/rafiki/issues/225
- https://github.com/interledger/rafiki/issues/2227

**Comment by BlairCurrey** [comment]
@sabineschaller  @mkurapov 

The `withdrawEventLiquidity` mutation tests include a case for the `wallet_address.web_monetization` event which got me wondering - are we currently or can we handle that without `withdrawEventLiquidity`? As far as I can see this is not handled in the MASE webhook server despite the [the integration docs saying it “should withdraw that liquidity from the wallet address and credit the receiver’s account”](wallet_address.web_monetization). Looks like maybe implementing that handler in the MASE using `createWalletAddressWithdrawal` should be an additional task on this story.

**Comment by mkurapov** [comment]
> Looks like maybe implementing that handler in the MASE using createWalletAddressWithdrawal should be an additional task on this story?

I think that makes sense, however, I believe in order to receive the `wallet_address.web_monetization` event we need to call the `triggerWalletAddressEvents` admin API which we are not doing from the MASE. Do you think it's worth adding the `wallet_address.web_monetization` handler if we don't have anything in place for `triggerWalletAddressEvents` yet?

Speaking of `triggerWalletAddressEvents`, maybe it's worth renaming that as well?

**Comment by BlairCurrey** [comment]
After speaking with Max we concluded a few things:
- currently `withdrawEventLiquidity` creates a withdrawal using the event id which ensures duplicate transfers for the same event are not created. We concluded that we can look this up internally in the new endpoints (as opposed to passing it in, or using some other id). For example, in the new `withdrawIncomingPaymentLiquidity` resolver we can get the latest webhook event where `withdrawalAccountId` is `incomingPayment.id` and `type` is either `incoming_payment.completed` or `incoming_payment.expired`. And similar for the other new endpoints
- we can implement a `handleWalletAddressWebMonetization` that calls `createWalletAddressWithdrawal` and test that manually and leave the MASE `triggerWalletAddressEvents` call out of scope due to complexity. I made an issue for that which includes more details on how to manually test.

**Comment by BlairCurrey** [comment]
Branch off [bc/1697/deprecate-event-liquidity](https://github.com/interledger/rafiki/tree/bc/1697/deprecate-event-liquidity) for these story issues. Will collect all the changes there before merging into main.
