### ISSUE TITLE
Update rates to be more intuitive

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1711]
## Context
Currently, the rates in the MASE are "inversed", and not necessarily intuitive:
https://github.com/interledger/rafiki/blob/bf3bc665c219200baa62cdb79f7bd0118d6caeee/localenv/mock-account-servicing-entity/app/routes/rates.ts#L8-L21

Reading this, IMO, it seems as though the rate is 1 USD = 1.16 EUR, which is not true (although possible of course). What is true is 1 USD = 1 / 1.16 ~ 0.8620 EUR. 

This is the (trickled-up) result of what `rates` are when it comes to the ILP quote. From the ILP pay [documentation](https://github.com/interledgerjs/interledgerjs/tree/master/packages/pay#exchange-rates): 

> Exchange rates are represented as the ratio between a destination amount and a source amount, in fractional units.

+ (see [comment](https://github.com/interledgerjs/interledgerjs/blob/fba2dfe8da2e582205632cbbc9433253b7956416/packages/pay/src/index.ts#L343-L346) in the startQuote function)

This means that to ILP pay, these rates
```
{
    USD: 1
    EUR: 1.12
}
```
can be more specifically represented like:
```
{
    USD/USD: 1
    USD/EUR: 1.12
}
```

In my opinion, we should have the `/rates` API be more intuitive for integrators (and in-line with actual FX APIs):
https://www.exchangerate-api.com/docs/standard-requests
https://www.fastforex.io/
https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1/latest/currencies/usd.json

to return something like
```
  USD: {
    EUR: 0.89,
    ZAR: 18.7
  },
  EUR: {
    USD: 1.12,
    ZAR: 20.48
  },
```
where it represents 1 USD = 0.89 EUR.

## Todos
- [ ] Return correct rates in the MASE to represent exchange rates for base as shown above
- [ ] Update rates service to handle updated rates
- [ ] Update any ilp pay arguments as necessary
