### ISSUE TITLE
Auto-peering: update `createPeerByUrl` mutation

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1765]
## Context
Now that we have the `POST /peer` route that returns ILP connection details for the peers, we don't need to manually enter the `staticIlpAddress` for the peer: the rafiki instance can just fetch that information via `POST /peer`. As a result, we can create a new `createPeerByUrl` mutation:

## Todos
- [ ] Takes in `peerUrl` `assetId` `maxPacketAmount` `name`
- [ ] Call `POST <peerUrl>` with `{ staticIlpAddress, ilpConnectorAddress, asset: { code, scale }, httpToken }` to get back the request peer's `staticIlpAddress` `ilpConnectorAddress`, as well as generate an httpToken for the peering relationship. 
- [ ] Create the peer in the DB as normal
