### ISSUE TITLE
Add `POST /peer` route handler

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1802]
## Context
By adding a `POST /peer` route handler, we can supply the peer information that it needs to make the peering connection on its own side, as well as return the necessary information for the requesting Rafiki to create the peer locally. This route will be the main connection point between two peers trying to connect, and exchange peering information.

## Todos
- [ ] Create a POST `/peer` handler to the existing "peering" service built in #1763. The request will take in `{ staticIlpAddress, ilpConnectorAddress, asset: { code, scale }, httpToken }` as the arguments.

Within the handler:
- [ ] Call the peerService.createPeer method internally, to create the (requesting) peer locally in the DB
- [ ] If peering creation was successful, return the configured `staticIlpAddress` `ilpConnectorAddress` so the requesting peer can connect on it's own end
