### ISSUE TITLE
Add fees to Admin UI

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1834]
## Context

Admins can now [set fees](https://github.com/interledger/rafiki/blob/ba69b0c301c3caf439a2f1ddee8f8b4d0fdaddab/packages/backend/src/graphql/schema.graphql#L185-L187) using the admin API. This is per asset. We could add the following features to the Admin UI:
* view the current fee per asset
  * I’d add that to the asset overview
* view all fees per asset set so far (fees are not updated, we just add new ones)
  * that would be a new table in a new view that you can probably access from the asset overview
* set (or add) a new fee
  * I’d also add that to the asset overview, in the same way we update other resources

## Todos
- [x] add a query to fetch all historic fees associated with a particular asset
- [x] add current fee to asset overview
- [x] allow setting a new fee on asset overview
- [x] show a table of all fees ever set when clicking somewhere on the asset overview
