### ISSUE TITLE
[Telemetry] - Instrument Rafiki

### ISSUE THREAD

**Issue by beniaminmunteanu** [interledger/rafiki#1913]
## Context
In order to add telemetry features for Rafiki, We need to instrument rafiki to collect and expose metrics according to the Opentelemetry standard.

## Tech:
We should creating a pipeline for collecting, analysing, and visualizing metrics in regards to **transactions** by using the respective set of technologies : Opentelemetry, Prometheus, Grafana.

- We will be opting for a sidecar pattern, and have rafiki push metrics to a new (configurable) dependency:
[The Opentelemetry Collector.](https://hub.docker.com/r/otel/opentelemetry-collector)

- The Otel collector will push metrics to an AWS Prometheus

- Grafana should have Prometheus as a datasource and provide dashboards

(uses instances created in) #1906 

As such, we will first attempt to visualize the following data (aggregated in daily, weekly & monthly):

- How many transactions were in the ILP network 
- What is the average amount in transactions
- What is the total transactions amount

## Todos
- [x] Add the Opentelemetry Collector as a configurable dependency
- [x] Add the Opentelemetry SDK
- [x] Collect transaction metrics
- [x] Periodically send metrics to Opentelemetry Collector
- [x] Authenticate Opentelemetry Collector in AWS
- [x] Send metrics from opentelemetry collector to AWS Prometheus
- [x] Send the transaction amount in USD to to Opentelemetry Collector and AWS Prometheus

## Linked Issues:

- #1925
