### ISSUE TITLE
Allow passing private key to signature service

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#1947]
## Context

The signature service that we use to generate signatures for Open Payments requests locally (using postman) currently generates or loads a key from disk. We want to change it such that POST requests to it also include an optional private key in the body to sign the requests with.

EDIT: We want to convert this into an AWS lambda such that it's not required for local or remote testing using Postman.

## Todos
- [ ] update POST endpoint
- [ ] move into AWS lambda
- [ ] update postman collection
