### ISSUE TITLE
[Telemetry] Set up AWS Prometheus & Grafana

### ISSUE THREAD

**Issue by beniaminmunteanu** [interledger/rafiki#1956]
## Context
Rafiki's Telemetry Feature now exposes metrics on the OpenTelemetry Standard, through an OpenTelemetry Collector Instance.
We should be able to gather metrics from all Rafiki instances, analyse and visualize them.
## Todos

- [x] Set up Managed Prometheus
- [x] Set up Managed Grafana with Prometheus as a Data source

- [x] Create an IAM user for OpenTelemetryCollector
- [x] Get access keys for the Opentelemetry collector user 
- [x] Use Access Keys to authenticate opentelemetry collectors
- [x] Create Role with write permissions to prometheus
- [x] Have collector IAM users use "assume role" in order to get write permissions to prometheus
