### ISSUE TITLE
Mojaloop as a payment method

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1965]
## Context
Currently, we are looking to add support for Mojaloop payments to support our use case for cross-border, remittance payments in the US, Mexico corridor. This requires:
- abstracting away some of the ILP related code we have in Rafiki to be more method-agnostic
- adding Mojaloop payment method in Open Payments, Rafiki. 
- adding our own Mojaloop connector similar to the ILP connector we currently have

Mojaloop Identity Lookup within Rafiki:
![identity-lookup](https://github.com/interledger/rafiki/assets/15069181/193ce2cf-9ffb-4636-848d-2bab37d6bf9c)

Mojaloop quote within Rafiki:
![quote](https://github.com/interledger/rafiki/assets/15069181/3aa95ff6-62da-4657-b7b0-93c99ee38be7)

Mojaloop transfer within Rafiki:
![transfer](https://github.com/interledger/rafiki/assets/15069181/abbdd985-5bf8-41cf-a8c4-d71d47eff94e)

## Todos
- [x] Create `payment-method` directory, move ILP related files into own directory (closed by https://github.com/interledger/rafiki/pull/1961)
- [ ] Update Rafiki to use new Open Payments spec with Incoming Payment & Quote payment method (https://github.com/interledger/open-payments/pull/284)
- [x] #1967
- [x] #1999
- [x] #1989
- [x] #1991
- [x] #1995
- [x] #1996
- [x] #1997
- [x] #1998
- [x] #2000
- [ ] (Optional) rename peering mutations from `createPeer...` to `createIlpPeer...`

**Comment by mkurapov** [comment]
Closing in favour of larger Rafiki architecture [overhaul](https://github.com/orgs/interledger/projects/6/views/1?pane=issue&itemId=43212773)

**Comment by mkurapov** [comment]
Closing in favour of larger Rafiki architecture [overhaul](https://github.com/orgs/interledger/projects/6/views/1?pane=issue&itemId=43212773)
