### ISSUE TITLE
Create "payment method handler" service, that abstracts away quoting & paying

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1967]
In order to be able to support multiple payment methods, we need a service that knows how to do quoting and transfers **without** having the callers of the service (QuoteService, OutgoingPaymentService) know exactly about the details of _how_ quoting and paying are done for different payment methods.

## Tasks
- [x] Introduce "payment method handler" service that abstracts away quoting and paying
- [x] Have `quoteService.createQuote` call the "payment manager" service "getQuote" method
- [ ] Move ILP quoting & transfers into own service
- [ ] Have `outgoingPaymentService` call the "payment manager" service "pay" method
