### ISSUE TITLE
Remove `hostname` from local playground

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1969]
## Context
In order to make it easier to run the playground locally with the postman collection, and to be able to test the Open Payments SDK/client against the local Rafiki instances, we should remove the `hostname` headers (`cloud-nine-wallet` `happy-life-bank`) from the docker compose files in the local playground setup.

## Todos
- [ ] Remove `hostname` from the local playground docker compose files
- [ ] Update the seed scripts to use the localhost hostname instead
- [ ] Remove `host` headers from the Postman requests (and signature signing)

**Comment by harshalkh** [comment]
I think I can pick this up and work on it. Could you please assign this to me @mkurapov @sabineschaller

**Comment by mkurapov** [comment]
Assigned @harshalkh, thanks for the contribution!
