### ISSUE TITLE
Create Mojaloop OpenAPI scheme & client library

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#1989]
## Context
In order to be able to make Mojaloop payments work between Rafiki's, we need to create an OpenAPI schema that contains the specifications for the Mojaloop requests: `/mj-quote` `/mj-transfer`.

Then, similar to the `token-introspection` library we have (ie `TokenIntrospectionClient`), we should create a Mojaloop connector client that is able to make these requests, validate the responses and provide proper types during usage.

## Todos

- [ ] Create OpenAPI spec for the Mojaloop connector 
- [ ] Add the ability to generate typescript types from the Mojaloop Connector OpenAPI spec
- [ ] Create `client/mojaloop-connector` folder within `payment-methods/mojaloop` that will contain the Mojaloop connector client
- [ ] Use generated typescript types in the client for making two API calls: `getQuote` and `createTransfer` (or something similar)
- [ ] Validate the responses via the OpenAPI spec

**Comment by mkurapov** [comment]
Closing in favour of larger Rafiki architecture [overhaul](https://github.com/orgs/interledger/projects/6/views/1?pane=issue&itemId=43212773)
