### ISSUE TITLE
Remove Event Liquidity Resolvers

### ISSUE THREAD

**Issue by BlairCurrey** [interledger/rafiki#2227]
# Context

#1693 adds new resolvers which should remove the need for these.

# Depends on

- https://github.com/interledger/rafiki/issues/1693
- giving integrators enough time to migrate

# Todos
- [x] Remove resolvers `WithdrawEventLiquidity`, `DepositEventLiquidity`
- [x] Remove references from docs.
- [x] Remove requests from postman
- [x] Look for any stray references from elsewhere and remove/ensure they are handled

**Comment by sabineschaller** [comment]
Do you think we should hold off on this and just label the event liquidity endpoints as deprecated? Just to give our current integrators a bit of time to swap?

**Comment by BlairCurrey** [comment]
I suppose that would be wise. I'll just take it off the parent.
