### ISSUE TITLE
Make quoting optional for creating an outgoing payment

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2409]
## Context

see Roadmap:
- https://github.com/interledger/rafiki/issues/2573

prerequisite: 
- https://github.com/interledger/open-payments/issues/415

## Todos
- [x] change resource server implementation
- [x] change graphl create outgoing payment resolver
- [x] https://github.com/interledger/open-payments/issues/415
