### ISSUE TITLE
Bruno follow up fixes

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2458]
## Context

We didn't address all the potential improvements in the [original Bruno PR](https://github.com/interledger/rafiki/pull/2422). Here is what still can be done.

## Todos
- [x] [add an environment for autopeering](https://github.com/interledger/rafiki/pull/2422#discussion_r1505723079)
- [x] [rename collection `Interledger` -> `Rafiki`](https://github.com/interledger/rafiki/pull/2422#discussion_r1505825401)
- [x] [improve "how to get collection into bruno" section in the docs
](https://github.com/interledger/rafiki/pull/2422#discussion_r1505827092)
- [x] [have a root script](https://github.com/interledger/rafiki/pull/2422#discussion_r1505849343)
- [x] [mention interaction ref in the OP example guide](https://github.com/interledger/rafiki/pull/2422#discussion_r1505863705)
- [x] [potentially make clientPrivateKey public](https://github.com/interledger/rafiki/pull/2422#discussion_r1505854344)

**Comment by AlexLakatos** [comment]
The Bruno collection links in the docs are broken. They use the pattern https://github.com/interledger/rafiki/main/bruno/collections/Interledger.

**Comment by sabineschaller** [comment]
On it.
