### ISSUE TITLE
Frontend Testing

### ISSUE THREAD

**Issue by JoblersTune** [interledger/rafiki#2499]
## Context
Currently there are no tests for the Rafiki `fronted` package.
## Todos
- [ ] Discuss and decide how much testing we want here
- [ ] What type of tests and which framework
- [ ] How extensive should test coverage be
