### ISSUE TITLE
Add logs in graphql resolvers - backend

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2575]
### Context

We want to add logs to all the graphql resolvers on the backend.

UPDATE:
When working on this, @sabineschaller realized that we don't handle errors the same way in queries and mutations. In queries, we throw errors, whereas in mutations, we treat them as data. To be consistent and to be able to use the apollo plugin for logging, we should move away from the error as data approach and just throw `GraqhQLError`s when something goes wrong in the resolvers. 

### Todos
- [x] add apollo plugin to log errors
- [x] update GraphQL schema
- [ ] update resolvers to throw instead of treating errors as data
- [ ] update MASE to handle new resolver behavior
- [ ] update docs
- [ ] potentially update bruno collection (scripts/tests)
