### ISSUE TITLE
Admin UI changes from workweek

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2681]
## Context
In Cluj for the breakpoint work week, we ended up going over the current state of the Admin UI, and came up with a few changes that we should address:

## Todos
- [ ] Rename “Webhooks” tab to “Webhook Events”
- [ ] Swap assets tab with peer tab (since we need Assets first to have Peers)
- [ ] Tooltips/descriptions over each of the input fields in the peering page (in general, more descriptions/links out to the docs)
