### ISSUE TITLE
Remove env variable defaults

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2683]
## Context

During the workweek in Cluj, we went through the list of env variables in `backend` and `auth` and changed some defaults. We also crystalized a list of variables that should not have defaults (set to none). The containers should not spin up if those variables are not set. For the local playground, we can define those in the docker-compose.

Backend defaults:
- ENABLE_TELEMETRY: false (set to true in local playground)
- OPEN_PAYMENTS_URL: \<None\>
- ILP_ADDRESS: \<None\>
- ILP_CONNECTOR_ADDRESS: \<None\>
- STREAM_SECRET: \<None\>
  - info on how that should be generated
- USE_TIGERBEETLE: true
- INSTANCE_NAME: \<None\>
- EXCHANGE_RATES_URL: \<None\>
- AUTH_SERVER_GRANT_URL: \<None\>
- AUTH_SERVER_INTROSPECTION_URL: \<None\>
- WEBHOOK_URL: \<None\>
- SIGNATURE_SECRET: \<None\>
- KEY_ID: \<None\>
- SPSP_ENABLED: True
   - Rename this to ENABLE_INTERLEDGER_PAYMENT_POINTERS

Auth defaults:
- IDENTITY_SERVER_DOMAIN:  \<None\>
   - Rename to IDENTITY_SERVER_URL
- AUTH_SERVER_DOMAIN:  \<None\>
- Rename AUTH_SERVER_DOMAIN to AUTH_SERVER_URL
- IDENTITY_SERVER_SECRET:  \<None\>
  - info on how that should be generated
- COOKIE_KEY:  \<None\>

## Todos
- [x] #2684
- [x] #2685
- [ ] make sure container does not start if variables are not set
- [ ] set variables in playground docker-compose
- [ ] improve documentation of env variables
