### ISSUE TITLE
[backend] update env vars and remove defaults

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2684]
Backend defaults:
- ENABLE_TELEMETRY: false (set to true in local playground)
- OPEN_PAYMENTS_URL: \<None\>
- ILP_ADDRESS: \<None\>
- ILP_CONNECTOR_ADDRESS: \<None\>
- STREAM_SECRET: \<None\>
- USE_TIGERBEETLE: true
- INSTANCE_NAME: \<None\>
- EXCHANGE_RATES_URL: \<None\>
- AUTH_SERVER_GRANT_URL: \<None\>
- AUTH_SERVER_INTROSPECTION_URL: \<None\>
- WEBHOOK_URL: \<None\>
- SIGNATURE_SECRET: \<None\>
- KEY_ID: \<None\>
- SPSP_ENABLED: True
   - Rename this to ENABLE_INTERLEDGER_PAYMENT_POINTERS

## Todos
- [x] update defaults
- [x] make sure container does not start if variables are not set
- [x] set variables in playground docker-compose
- [x] improve documentation of env variables
