### ISSUE TITLE
[auth]: update env vars and remove defaults

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2685]
Auth defaults:
- IDENTITY_SERVER_DOMAIN:  \<None\>
   - Rename to IDENTITY_SERVER_URL
- AUTH_SERVER_DOMAIN:  \<None\>
- Rename AUTH_SERVER_DOMAIN to AUTH_SERVER_URL
- IDENTITY_SERVER_SECRET:  \<None\>
- COOKIE_KEY:  \<None\>

## Todos
- [x] update defaults
- [x] make sure container does not start if variables are not set
- [x] set variables in playground docker-compose
- [x] improve documentation of env variables
