### ISSUE TITLE
Allow `createWalletAddress` mutation to take in additional properties

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2739]
### Context
During wallet address creation, we want to let the ASE allow to add additional properties to be associated with the wallet address.

We need to update the `createWalletAddress` mutation input to take in additionalProperties.
These properties would be optionally visible when requesting a wallet address through Open Payments. The input is an optional array of objects with `key` & `value` and `visibleInOpenPayments` (suggested name), a flag that enables or disables this field from appearing in Open Payments Wallet Address lookup.

### Tasks
- [x] Update `createWalletAddress` mutation input
- [x] Store these fields in a new table with structure: `walletAddressId: FK` `fieldKey: string` `fieldValue: string` `visibleInOpenPayments: bool`, `createdAt: Date`, `updatedAt: Date`)
- [x] Expose these new fields when fetching wallet address via Open Payments (making sure to show only fields that are indeed enabled for visibility for Open Payments)
- [x] Expose these new fields when fetching wallet address via the Admin API
- [x] Update the documentation

### PR
https://github.com/interledger/rafiki/pull/2752
