### ISSUE TITLE
Allow `updateWalletAddress` mutation to take in additional properties

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2740]
### Context
Similar to wallet address creation in #2739, we want to let the ASE allow updating additional properties to be associated with the wallet address.

We need to update the `updateWalletAddress` mutation input to take in `additionalProperties`.
These properties are the same as the `createWalletAddress` input: an optional array of objects with `key` & `value` and `visibleInOpenPayments`.

### Tasks
- [x] Update `updateWalletAddress` mutation input to take in additional params
- [x] Update these new fields in the new wallet address table, hard deleting keys that are no longer used
- [x] Update Documentation, including update behavior (overrides entire `additionalFields` on each update)
