### ISSUE TITLE
Treat rates as composite exchange and network rates

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2742]
## Context

Currently, Rafiki requires an exchange rates endpoint `EXCHANGE_RATES_URL`, that provides exchange rates in the format
```js
{
  base: "CURRENCY_CODE_0",
  rates: {
    "CURRENCY_CODE_1": value, // exchange rate
    ...
  }
}
```
However, as soon as we enable multi-hop routing, the rates should not just reflect the exchange rates but also the fee of forwarding packets. No middle connector would want to forward the packets for free. Hence, we need to update the endpoint to be called `RATES_URL` again and to change the expected response to be of the form
```js
{
  base: "CURRENCY_CODE_0",
  rates: {
    "CURRENCY_CODE_0": value, // just forwarding fees
    "CURRENCY_CODE_1": value,  // exchange rate + exchange fee + forwarding fee
    ...
  }
}
```

## Todos
- [ ] rename `EXCHANGE_RATES_URL` to `RATES_URL`
- [ ] rename `EXCHANGE_RATES_LIFETIME` to `RATES_LIFETIME`
- [ ] rename and update OpenAPI spec
- [ ] update docs to explain expected behavior
