### ISSUE TITLE
Configure Rafiki to be able to track traces

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2808]
### Context

Adding [traces](https://opentelemetry.io/docs/concepts/signals/traces/) to Rafiki will give us useful insights into different parts of the code, and how each operation runs, like network requests, PSQL queries, and particular sections of code (e.g. ILP payments). 

This is an example trace from Grafana:

![Image](https://github.com/user-attachments/assets/03a55666-f168-49cf-8b69-b8626c82f10d)

In the above, each block represents "spans" and corresponding nested "spans" that show different kind of attributes like what the operation was, metadata, and how long each operation took.

These spans can be created manually within the code, but also automatically. 

There are a lot of auto-instrumentation packages available for us to use (PSQL auto-instrumentation, GraphQL, Koa etc), which will enable tracing (mostly) out of the box. 

Since we have added a telemetry stack within the local playground in #2800, we can also add an service that ingests traces via the OpenTelemetry APIs. This service is [Grafana Tempo](https://grafana.com/oss/tempo/) , and it will take traces sent from the Rafiki backend, and be able to serve as a data source for the Grafana frontend.

### Tasks
- [ ] Add option to collect traces in Rafiki (under an env flag)
- [ ] Add Grafana Tempo to local playground stack
- [ ] Add basic auto-instrumentation packages (GraphQL, PSQL, HTTP)
