### ISSUE TITLE
Cache assets

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#2981]
### Context

During Rafiki WW, one of the performance optimizations we found to be useful is caching assets, given we make so many requests for assets, even though they rarely change. 

We should use redis for caching these.

### Todo
- [x] Remove `public abstract asset: Asset` from `WalletAddressSubresource` model, and instead, add a getter and a setter for the field. (We don't want to use Objection to fetch assets through foreign keys)
- [x] Add redis cache to assetService (via `createRedisDataStore`, and a reasonable key expiry). Delete cache on asset `update`.
- [x] Resolve any requests for assets via the assetService instead of any `.withGraphFetched('asset')` objection calls, use setter on `WalletAddressSubresource` model to add asset to model

**Comment by koekiebox** [comment]
Note, the Redis cache was replaced in favour of the temporary local cache. The local cache stores the data for 5 seconds.
