### ISSUE TITLE
Frontend environment variables

### ISSUE THREAD

**Issue by sabineschaller** [interledger/rafiki#2994]
## Context

When the tech writers went through the frontend environment variables, we identified some gaps that we want to close. 

## Todos
- Environment variables
  - [ ] remove default for GRAPHQL_URL and make it required (i.e. app doesn't start if it's not set)
  - [ ] remove default for OPEN_PAYMENTS_URL and make it required
  - [ ] set NODE_ENV default to `production`
  - [ ] set ENABLE_INSECURE_MESSAGE_COOKIE to `true` and remove check for NODE_ENV
- Code
  - [ ] add KRATOS_ADMIN_URL to `variables` in packages/frontend/app/lib/envConfig.server.ts
  - [ ] change `start` command to `remix-serve ./build/index.js` in packages/frontend/package.json
- Docs
  - [ ] Update docs accordingly once _Environment variables_ and _Code_ changes have been done

**Comment by melissahenderson** [comment]
I'm removing the user-docs tag because of 3042. I'm also watching this issue so I'll know when it's merged.
