### ISSUE TITLE
Set default limit for `accountingTransfers` backend API

### ISSUE THREAD

**Issue by mkurapov** [interledger/rafiki#3003]
## Context
Currently, in our `accountingTransfers` query in the backend API, because we do not yet have pagination, we only allow providing a `limit` value to how many transfers are returned. For this query, when using Tigerbeetle, we have a limit set to 100_000. This is also what is mentioned in the description. 

We should set a smaller default `limit` for both accounting services, (20?) and make sure to update the description in the GraphQL API to be accounting service agnostic.

## Todos
- [ ] Update `limit` in both of the accounting services to be 20 for fetching transfers
- [ ] Update GraphQL API description 
- [ ] Tag writer @brad-dow to take a look at the description change

**Comment by NawinKumarSharma** [comment]
@mkurapov can you assign me?

**Comment by sabineschaller** [comment]
@NawinKumarSharma It's yours! 🙂
